version: '3.3'
services:
  e2e-test:
    container_name: e2e-test
    build:
      context: .
    depends_on:
      - spp-platform
    links:
      - spp-platform
    ports:
      - "5000:5000"
    environment:
      - SPP_PLATFORM_HOST=spp-platform
  spp-platform:
    image: sourceplusplus/spp-platform:latest
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      - SPP_LOGGING_LEVEL=trace
