name: Run Tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.svg'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.svg'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python -m unittest discover -s ./tests
